name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Directory Structure
        run: ls -la  # Debugging: Show files in the workspace

      - name: Set up Java & Maven
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: maven

      - name: Install Maven
        run: sudo apt-get install -y maven

      - name: Build Java Application
        run: |
          if [ -f "pom.xml" ]; then
            mvn clean package -DskipTests
          elif [ -d "Student-Management-System" ] && [ -f "Student-Management-System/pom.xml" ]; then
            cd Student-Management-System
            mvn clean package -DskipTests
          else
            echo "Error: pom.xml not found!"
            exit 1
          fi

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker Image
        run: |
          if [ -d "Student-Management-System" ]; then
            cd Student-Management-System
          fi
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Application
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest
          docker stop student-management || true
          docker rm student-management || true
          docker run -d -p 8080:8080 --name student-management ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest
