name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Runs on push to the main branch
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      # 🛠 FIX: Navigate to the correct directory where pom.xml exists
      - name: Build Java Application
        run: |
          cd Student-Management-System  # Change directory if needed
          ls -la  # Debugging: Check if pom.xml is present
          mvn clean package -DskipTests  # Run Maven build

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        run: |
          cd Student-Management-System  # Ensure we are in the correct directory
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest .

      - name: Push Docker Image to Docker Hub
        run: docker push ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy Application
        run: |
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest
          docker stop student-management || true
          docker rm student-management || true
          docker run -d -p 8080:8080 --name student-management ${{ secrets.DOCKER_HUB_USERNAME }}/student-management-system:latest
