name: Unzip File

on:
  push:
    branches:
      - main  # Change to your branch if needed

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Unzip File
        run: unzip your-zip-file.zip -d destination-folder
